### ISSUE TITLE
Demo Customer - Joe Q Public

### ISSUE THREAD

**Issue by samhamilton** [moqui/mantle#28]
Hi David, 

In the demo data of Joe Q Public (mantle-udm/data/ZzbOrganizationDemoData.xml) I am trying to understand why its missing roleTypeId, is this on purpose? 

From what I see of the other demo data I belive its missing these two: 
- ` <mantle.party.PartyRole partyId="CustJqp" roleTypeId="Customer"/> `
- ` <mantle.party.PartyRole partyId="CustJqp" roleTypeId="CustomerBillTo"/> `

Thanks
Sam

**Comment by jonesde** [comment]
Mantle is designed to not require parties to have a PartyRole record in order to use that role to describe the party's relationship with another entity like an order. For a customer party like this it is nice to not require a much extra data when creating a new one, and in this case that includes these roles. It may be helpful for certain queries and analysis, and can certainly be done in code to create new customers, but isn't required by the data model or services.

**Comment by samhamilton** [comment]
OK, so its up to the developer of the crust app to add them if they get more than one type of customer as and when needed, if they only have one type of customer no problem and not required but later as you said it good for certain queries and analytics 

Thanks! 
Sam
