### ISSUE TITLE
product.maintenance.AssetMeter - More than one Meter on an Asset (PK issue)

### ISSUE THREAD

**Issue by ronankeane** [moqui/mantle#52]
Should 'productMeterId' (as well as 'assetId' and 'readingDate') be a primary key?

If multiple meters on the same asset are recorded on the same date, that will cause a problem.

**Comment by jonesde** [comment]
If two meter readings happened in the same millisecond it would be a problem, otherwise it wouldn't. A date-time field, in many cases anyway, is an adequate alternative to a sequenced key and that would be the only alternative for the AssetMeter entity because the idea is the entity may be used for meter readings for configured ProductMeters (using productMeterId) or for non-configured meters by type (using productMeterTypeId).
